title: RGH Optimize for Windows
author: Rayen Ghanmi
description: Use Windows the way it meant to be !!
remote_theme: "dracula/gh-pages"
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
