title: RGH Optimize for Windows by Rayen Ghanmi
author: Rayen Ghanmi
description: Use Windows the way it meant to be !!
remote_theme: zivong/jekyll-theme-hamilton
skin: midnight
#"dracula/gh-pages"
avatar: "/img/ico.png"
